#!/bin/bash
export PATH="/Users/dan.nagao/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
export HOME="/Users/dan.nagao"

LOG="/Users/dan.nagao/kindle-to-text/launch.log"
cd /Users/dan.nagao/kindle-to-text

/Users/dan.nagao/.local/bin/uv run app.py >> "$LOG" 2>&1
